NodeOUs:
  Enable: true
  # ClientOUIdentifier:
  #   Certificate: cacerts/0-0-0-0-7053.pem
  #   OrganizationalUnitIdentifier: client
  # PeerOUIdentifier:
  #   Certificate: cacerts/org0-ca-cert.pem
  #   OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/0-0-0-0-7053.pem
    OrganizationalUnitIdentifier: admin