version: "3.6"


networks:
  mynetwork.com:
    external: true
    name: cmd_smart-campus

services:
  caliper_2.2:
    container_name: caliper_2.2
    image: hyperledger/caliper:0.4.3-unstable-20210721141355
    command: launch manager --caliper-fabric-gateway-enabled ---caliper-flow-only-test
    environment:
      - CALIPER_BIND_SUT=fabric:2.2
      - CALIPER_WORKSPACE=/hyperledger/caliper/workspace
      - CALIPER_BENCHCONFIG=/hyperledger/caliper/workspace/benchmarks/myAssetBenchmark.yml
      - CALIPER_NETWORKCONFIG=/hyperledger/caliper/workspace/networks/networkConfig.yml
      - CALIPER_FABRIC_SKIPCREATECHANNEL_MYCHANNEL=true
      - loglevel=Debug
      # - CALIPER_FABRIC_GATEWAY_LOCALHOST=flase
      # -- --caliper-flow-only-test
    volumes:
      - ../caliper-workspace:/hyperledger/caliper/workspace/
    networks:
      - mynetwork.com